// AI Memory Systems Comparison — Data
// CC0 Public Domain. Add new systems by appending to the array.
// Last updated: 2026-05-27

const FEATURE_GROUPS = [
  {
    id: "vitals",
    label: "Vital Signs",
    features: [
      { id: "stars", label: "Stars", type: "number" },
      { id: "language", label: "Language", type: "text" },
      { id: "license", label: "License", type: "text" },
      { id: "singleBinary", label: "Single binary", type: "bool" },
    ]
  },
  {
    id: "architecture",
    label: "Architecture",
    features: [
      { id: "deployment", label: "Deployment", type: "text" },
      { id: "storage", label: "Storage", type: "text" },
      { id: "integration", label: "Integration", type: "text" },
      { id: "proxy", label: "Proxy", type: "bool" },
      { id: "webUi", label: "Web/TUI", type: "bool" },
      { id: "offline", label: "Offline", type: "bool" },
    ]
  },
  {
    id: "datamodel",
    label: "Data Model",
    features: [
      { id: "unit", label: "Storage unit", type: "text" },
      { id: "entities", label: "Entities", type: "bool" },
      { id: "actions", label: "Actions", type: "bool" },
      { id: "keywords", label: "Keywords/tags", type: "bool" },
      { id: "anticipatedQueries", label: "Anticipated queries", type: "bool" },
      { id: "triggerRules", label: "Trigger rules", type: "bool" },
      { id: "domainTag", label: "Domain tag", type: "bool" },
      { id: "taskType", label: "Task type", type: "bool" },
      { id: "context", label: "Context (why)", type: "bool" },
      { id: "source", label: "Source attribution", type: "bool" },
      { id: "originTrust", label: "Origin + trust", type: "bool" },
      { id: "emotional", label: "Emotional", type: "bool" },
      { id: "conflict", label: "Conflict surfacing", type: "bool" },
      { id: "layeredMemory", label: "Layered memory", type: "bool" },
      { id: "timeTravel", label: "Time-travel", type: "bool" },
      { id: "schemaFields", label: "Schema fields", type: "number" },
    ]
  },
  {
    id: "search",
    label: "Search & Retrieval",
    features: [
      { id: "fulltext", label: "Full-text", type: "bool" },
      { id: "semantic", label: "Semantic/vector", type: "bool" },
      { id: "hybrid", label: "Hybrid (BM25+Vec)", type: "bool" },
      { id: "deep", label: "Deep (incl. thinking)", type: "bool" },
      { id: "codeGraph", label: "Code graph", type: "bool" },
      { id: "docsSearch", label: "Docs search", type: "bool" },
      { id: "factQuery", label: "Fact metadata query", type: "bool" },
      { id: "timeline", label: "Timeline view", type: "bool" },
      { id: "searchModes", label: "Search modes", type: "number" },
      { id: "dataSources", label: "Data sources", type: "number" },
    ]
  },
  {
    id: "lifecycle",
    label: "Knowledge Lifecycle",
    features: [
      { id: "decay", label: "Decay/forgetting", type: "bool" },
      { id: "supersede", label: "Supersede/replace", type: "bool" },
      { id: "contradiction", label: "Contradiction detect", type: "bool" },
      { id: "quarantine", label: "Quarantine", type: "bool" },
      { id: "autoResolve", label: "Auto-resolution", type: "bool" },
      { id: "trustModel", label: "Trust model", type: "bool" },
      { id: "explicitForget", label: "Explicit forget", type: "bool" },
    ]
  },
  {
    id: "extraction",
    label: "Extraction Pipeline",
    features: [
      { id: "autoExtract", label: "Auto-extraction", type: "bool" },
      { id: "contentPreproc", label: "Content-aware preproc", type: "bool" },
      { id: "dedup", label: "Deduplication", type: "bool" },
      { id: "qualityRefine", label: "Quality refinement", type: "bool" },
      { id: "narrative", label: "Narrative generation", type: "bool" },
      { id: "clustering", label: "Clustering", type: "bool" },
      { id: "recurrence", label: "Recurrence detection", type: "bool" },
      { id: "persona", label: "Persona extraction", type: "bool" },
    ]
  },
  {
    id: "platform",
    label: "Platform Support",
    features: [
      { id: "p_claude", label: "Claude Code", type: "bool" },
      { id: "p_codex", label: "Codex", type: "bool" },
      { id: "p_opencode", label: "OpenCode", type: "bool" },
      { id: "p_gemini", label: "Gemini CLI", type: "bool" },
      { id: "p_copilot", label: "Copilot", type: "bool" },
      { id: "p_cursor", label: "Cursor", type: "bool" },
      { id: "p_windsurf", label: "Windsurf", type: "bool" },
      { id: "p_openclaw", label: "OpenClaw", type: "bool" },
      { id: "p_hermes", label: "Hermes", type: "bool" },
      { id: "p_pi", label: "pi/omp", type: "bool" },
      { id: "p_antigravity", label: "Antigravity", type: "bool" },
    ]
  },
  {
    id: "benchmarks",
    label: "Benchmarks (published)",
    features: [
      { id: "b_locomo", label: "LoCoMo", type: "text" },
      { id: "b_longmemeval", label: "LongMemEval", type: "text" },
      { id: "b_personamem", label: "PersonaMem", type: "text" },
      { id: "b_token", label: "Token reduction", type: "text" },
      { id: "b_methodology", label: "Methodology open", type: "bool" },
    ]
  },
];

const SYSTEMS = [
  {
    id: "claude-mem",
    name: "claude-mem",
    url: "https://github.com/thedotmack/claude-mem",
    description: "Hooks-based observation capture with progressive disclosure",
    stars: 79000, language: "TypeScript", license: "Apache 2.0", singleBinary: false,
    deployment: "Local CLI", storage: "SQLite+Chroma", integration: "Hooks (5)", proxy: false, webUi: true, offline: true,
    unit: "Observation (text)",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 4,
    fulltext: true, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: true, searchModes: 3, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: true, p_gemini: true, p_copilot: true, p_cursor: false, p_windsurf: false, p_openclaw: true, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "mem0",
    name: "Mem0",
    url: "https://github.com/mem0ai/mem0",
    description: "Memory-as-a-Service platform with best published benchmarks",
    stars: 57000, language: "Python", license: "Apache 2.0", singleBinary: false,
    deployment: "Lib/Self-host/Cloud", storage: "Qdrant", integration: "API/SDK", proxy: false, webUi: true, offline: false,
    unit: "Memory (text)",
    entities: true, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 6,
    fulltext: true, semantic: true, hybrid: true, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: "add-only", contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: true,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: true, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "91.6", b_longmemeval: "94.8", b_personamem: "—", b_token: "—", b_methodology: true,
  },
  {
    id: "engram",
    name: "engram",
    url: "https://github.com/Gentleman-Programming/engram",
    description: "Go binary agent memory with conflict surfacing and TUI",
    stars: 3823, language: "Go", license: "MIT", singleBinary: true,
    deployment: "Local bin / Cloud (opt-in)", storage: "SQLite+FTS5", integration: "MCP+Hooks (19)", proxy: false, webUi: true, offline: true,
    unit: "Memory (What/Why/Where/Learned)",
    entities: false, actions: false, keywords: true, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: true, source: false, originTrust: false, emotional: false, conflict: true, layeredMemory: false, timeTravel: true, schemaFields: 6,
    fulltext: true, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: true, searchModes: 4, dataSources: 1,
    decay: false, supersede: true, contradiction: true, quarantine: false, autoResolve: false, trustModel: false, explicitForget: true,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: true, p_gemini: true, p_copilot: false, p_cursor: true, p_windsurf: true, p_openclaw: false, p_hermes: false, p_pi: true, p_antigravity: true,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "graphiti",
    name: "Graphiti",
    url: "https://github.com/getzep/graphiti",
    description: "Temporal knowledge graph engine (powers Zep)",
    stars: 26700, language: "Python", license: "Apache 2.0", singleBinary: false,
    deployment: "Library", storage: "Graph DB", integration: "Library", proxy: false, webUi: false, offline: true,
    unit: "Fact (graph node)",
    entities: true, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: true, timeTravel: true, schemaFields: 8,
    fulltext: true, semantic: true, hybrid: true, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: true, supersede: true, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: false, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "cognee",
    name: "Cognee",
    url: "https://github.com/topoteretes/cognee",
    description: "Memory control plane with remember/recall/forget/improve API",
    stars: 17500, language: "Python", license: "Apache 2.0", singleBinary: false,
    deployment: "Lib/Cloud", storage: "Graph+Vector", integration: "API+Hooks", proxy: false, webUi: true, offline: false,
    unit: "Fact (graph+vec)",
    entities: true, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 10,
    fulltext: true, semantic: true, hybrid: true, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: true,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: true, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "byterover",
    name: "ByteRover",
    url: "https://github.com/campfirein/byterover-cli",
    description: "Context tree with git-like VC, strongest benchmarks (LoCoMo 96.1)",
    stars: 4795, language: "TypeScript", license: "Elastic 2.0", singleBinary: false,
    deployment: "Local CLI / Cloud", storage: "SQLite+Context tree", integration: "MCP+REPL", proxy: false, webUi: true, offline: true,
    unit: "Context node (tree)",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: true, schemaFields: 6,
    fulltext: true, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: true, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: false, p_gemini: false, p_copilot: true, p_cursor: true, p_windsurf: true, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "96.1", b_longmemeval: "92.8", b_personamem: "—", b_token: "—", b_methodology: true,
  },
  {
    id: "memvid",
    name: "Memvid",
    url: "https://github.com/memvid/memvid",
    description: "Single-file memory (.mv2) with Smart Frames and time-travel",
    stars: 15600, language: "Rust", license: "Apache 2.0", singleBinary: true,
    deployment: "Lib/Local file", storage: "Single .mv2 file", integration: "SDK", proxy: false, webUi: false, offline: true,
    unit: "Smart Frame",
    entities: false, actions: false, keywords: true, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: true, timeTravel: true, schemaFields: 8,
    fulltext: true, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: true, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: false, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "+35% SOTA", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: true,
  },
  {
    id: "memori",
    name: "Memori",
    url: "https://github.com/MemoriLabs/Memori",
    description: "Agent-native memory (captures execution, not just conversation)",
    stars: 15000, language: "Python", license: "Apache 2.0", singleBinary: false,
    deployment: "Cloud / BYODB", storage: "Cloud", integration: "SDK/MCP", proxy: false, webUi: true, offline: false,
    unit: "Memory entry",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 6,
    fulltext: true, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: true, p_windsurf: false, p_openclaw: true, p_hermes: true, p_pi: false, p_antigravity: false,
    b_locomo: "81.95", b_longmemeval: "—", b_personamem: "—", b_token: "95% fewer", b_methodology: true,
  },
  {
    id: "everos",
    name: "EverOS",
    url: "https://github.com/EverMind-AI/EverOS",
    description: "Self-evolving agent memory with evaluation framework",
    stars: 5700, language: "Python", license: "Apache 2.0", singleBinary: false,
    deployment: "Lib/MCP", storage: "Vector DB", integration: "MCP", proxy: false, webUi: false, offline: true,
    unit: "Memory entry",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 8,
    fulltext: true, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: true, p_gemini: true, p_copilot: false, p_cursor: true, p_windsurf: false, p_openclaw: true, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "✅", b_longmemeval: "✅", b_personamem: "—", b_token: "—", b_methodology: true,
  },
  {
    id: "tencentdb",
    name: "TencentDB-AM",
    url: "https://github.com/Tencent/TencentDB-Agent-Memory",
    description: "Mermaid symbolic memory, L0→L3 pyramid, 61% token reduction",
    stars: 4300, language: "TypeScript", license: "MIT", singleBinary: false,
    deployment: "Plugin (OpenClaw)", storage: "SQLite+sqlite-vec", integration: "Plugin hooks", proxy: false, webUi: false, offline: true,
    unit: "Atom/Scenario/Persona",
    entities: true, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: true, timeTravel: false, schemaFields: 12,
    fulltext: true, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: true,
    p_claude: false, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: true, p_hermes: true, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "76%", b_token: "61%", b_methodology: true,
  },
  {
    id: "yesmem",
    name: "YesMem",
    url: "https://github.com/carsteneu/yesmem",
    description: "Project continuity layer with deepest data model and proxy collapse",
    stars: 9, language: "Go", license: "Apache 2.0", singleBinary: true,
    deployment: "Local binary", storage: "SQLite+Vector", integration: "Proxy+MCP+Hooks", proxy: true, webUi: false, offline: true,
    unit: "Learning V2 (structured)",
    entities: true, actions: true, keywords: true, anticipatedQueries: true, triggerRules: true, domainTag: true, taskType: true, context: true, source: true, originTrust: true, emotional: true, conflict: true, layeredMemory: false, timeTravel: true, schemaFields: 22,
    fulltext: true, semantic: true, hybrid: true, deep: true, codeGraph: true, docsSearch: true, factQuery: true, timeline: true, searchModes: 9, dataSources: 4,
    decay: true, supersede: true, contradiction: true, quarantine: true, autoResolve: true, trustModel: true, explicitForget: true,
    autoExtract: true, contentPreproc: true, dedup: true, qualityRefine: true, narrative: true, clustering: true, recurrence: true, persona: true,
    p_claude: true, p_codex: true, p_opencode: true, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "0.87", b_longmemeval: "—", b_personamem: "—", b_token: "~30% proxy", b_methodology: true,
  },
  {
    id: "ai-memory",
    name: "ai-memory",
    url: "https://github.com/akitaonrails/ai-memory",
    description: "Git-versioned markdown wiki, zero LLM mode, cross-agent handoffs",
    stars: 324, language: "Rust", license: "MIT", singleBinary: true,
    deployment: "Local binary", storage: "Git wiki (md)", integration: "MCP+Hooks", proxy: false, webUi: true, offline: true,
    unit: "Wiki page (md)",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: true, schemaFields: 6,
    fulltext: true, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 2, dataSources: 1,
    decay: false, supersede: true, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: true, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: true, p_gemini: true, p_copilot: false, p_cursor: true, p_windsurf: false, p_openclaw: true, p_hermes: false, p_pi: true, p_antigravity: true,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "memory-palace",
    name: "Memory Palace",
    url: "https://github.com/AGI-is-going-to-arrive/Memory-Palace",
    description: "Forgetting engine, snapshot rollback, intent-aware search, 4 maintenance engines",
    stars: 300, language: "Python", license: "MIT", singleBinary: false,
    deployment: "Docker / local Python", storage: "SQLite+sqlite-vec", integration: "MCP+Skills", proxy: false, webUi: true, offline: true,
    unit: "Memory entry",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: true, timeTravel: true, schemaFields: 8,
    fulltext: true, semantic: true, hybrid: true, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 3, dataSources: 1,
    decay: true, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: true, qualityRefine: false, narrative: false, clustering: true, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: true, p_gemini: true, p_copilot: false, p_cursor: true, p_windsurf: true, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: true,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "mempalace",
    name: "MemPalace",
    url: "https://github.com/MemPalace/mempalace",
    description: "Verbatim storage, palace metaphor, 96.6% LongMemEval raw retrieval",
    stars: 53000, language: "Python", license: "MIT", singleBinary: false,
    deployment: "Local CLI", storage: "ChromaDB (pluggable)", integration: "CLI + MCP", proxy: false, webUi: false, offline: true,
    unit: "Verbatim text (no summarization)",
    entities: true, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 5,
    fulltext: false, semantic: true, hybrid: true, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 2,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: true, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "88.9", b_longmemeval: "96.6", b_personamem: "—", b_token: "—", b_methodology: true,
  },
];
