// AI Memory Systems Comparison — Data
// CC0 Public Domain. Add new systems by appending to the array.
// Last updated: 2026-05-27

const FEATURE_GROUPS = [
  {
    id: "vitals",
    label: "Vital Signs",
    features: [
      { id: "stars", label: "Stars", type: "number" },
      { id: "language", label: "Language", type: "text" },
      { id: "license", label: "License", type: "text" },
      { id: "singleBinary", label: "Single binary", type: "bool" },
      { id: "created", label: "Created", type: "text" },
      { id: "coverage", label: "Coverage", type: "number" },
    ]
  },
  {
    id: "architecture",
    label: "Architecture",
    features: [
      { id: "deployment", label: "Deployment", type: "text" },
      { id: "storage", label: "Storage", type: "text" },
      { id: "integration", label: "Integration", type: "text" },
      { id: "proxy", label: "Proxy", type: "bool" },
      { id: "webUi", label: "Web/TUI", type: "bool" },
      { id: "offline", label: "Offline", type: "bool" },
    ]
  },
  {
    id: "datamodel",
    label: "Data Model",
    features: [
      { id: "unit", label: "Storage unit", type: "text" },
      { id: "entities", label: "Entities", type: "bool" },
      { id: "actions", label: "Actions", type: "bool" },
      { id: "keywords", label: "Keywords/tags", type: "bool" },
      { id: "anticipatedQueries", label: "Anticipated queries", type: "bool" },
      { id: "triggerRules", label: "Trigger rules", type: "bool" },
      { id: "domainTag", label: "Domain tag", type: "bool" },
      { id: "taskType", label: "Task type", type: "bool" },
      { id: "context", label: "Context (why)", type: "bool" },
      { id: "source", label: "Source attribution", type: "bool" },
      { id: "originTrust", label: "Origin + trust", type: "bool" },
      { id: "emotional", label: "Emotional", type: "bool" },
      { id: "conflict", label: "Conflict surfacing", type: "bool" },
      { id: "layeredMemory", label: "Layered memory", type: "bool" },
      { id: "timeTravel", label: "Time-travel", type: "bool" },
      { id: "schemaFields", label: "Schema fields", type: "number" },
    ]
  },
  {
    id: "search",
    label: "Search & Retrieval",
    features: [
      { id: "fulltext", label: "Full-text", type: "bool" },
      { id: "semantic", label: "Semantic/vector", type: "bool" },
      { id: "hybrid", label: "Hybrid (BM25+Vec)", type: "bool" },
      { id: "deep", label: "Deep (incl. thinking)", type: "bool" },
      { id: "codeGraph", label: "Code graph", type: "bool" },
      { id: "docsSearch", label: "Docs search", type: "bool" },
      { id: "factQuery", label: "Fact metadata query", type: "bool" },
      { id: "timeline", label: "Timeline view", type: "bool" },
      { id: "searchModes", label: "Search modes", type: "number" },
      { id: "dataSources", label: "Data sources", type: "number" },
    ]
  },
  {
    id: "lifecycle",
    label: "Knowledge Lifecycle",
    features: [
      { id: "decay", label: "Decay/forgetting", type: "bool" },
      { id: "supersede", label: "Supersede/replace", type: "bool" },
      { id: "contradiction", label: "Contradiction detect", type: "bool" },
      { id: "quarantine", label: "Quarantine", type: "bool" },
      { id: "autoResolve", label: "Auto-resolution", type: "bool" },
      { id: "trustModel", label: "Trust model", type: "bool" },
      { id: "explicitForget", label: "Explicit forget", type: "bool" },
    ]
  },
  {
    id: "extraction",
    label: "Extraction Pipeline",
    features: [
      { id: "autoExtract", label: "Auto-extraction", type: "bool" },
      { id: "contentPreproc", label: "Content-aware preproc", type: "bool" },
      { id: "dedup", label: "Deduplication", type: "bool" },
      { id: "qualityRefine", label: "Quality refinement", type: "bool" },
      { id: "narrative", label: "Narrative generation", type: "bool" },
      { id: "clustering", label: "Clustering", type: "bool" },
      { id: "recurrence", label: "Recurrence detection", type: "bool" },
      { id: "persona", label: "Persona extraction", type: "bool" },
    ]
  },
  {
    id: "platform",
    label: "Platform Support",
    features: [
      { id: "p_claude", label: "Claude Code", type: "bool" },
      { id: "p_codex", label: "Codex", type: "bool" },
      { id: "p_opencode", label: "OpenCode", type: "bool" },
      { id: "p_gemini", label: "Gemini CLI", type: "bool" },
      { id: "p_copilot", label: "Copilot", type: "bool" },
      { id: "p_cursor", label: "Cursor", type: "bool" },
      { id: "p_windsurf", label: "Windsurf", type: "bool" },
      { id: "p_openclaw", label: "OpenClaw", type: "bool" },
      { id: "p_hermes", label: "Hermes", type: "bool" },
      { id: "p_pi", label: "pi/omp", type: "bool" },
      { id: "p_antigravity", label: "Antigravity", type: "bool" },
    ]
  },
  {
    id: "benchmarks",
    label: "Benchmarks (published)",
    features: [
      { id: "b_locomo", label: "LoCoMo", type: "text" },
      { id: "b_longmemeval", label: "LongMemEval", type: "text" },
      { id: "b_personamem", label: "PersonaMem", type: "text" },
      { id: "b_token", label: "Token reduction", type: "text" },
      { id: "b_methodology", label: "Methodology open", type: "bool" },
    ]
  },
];

const SYSTEMS = [
  {
    id: "claude-mem",
    name: "claude-mem",
    url: "https://github.com/thedotmack/claude-mem",
    description: "Hooks-based observation capture with progressive disclosure",
    stars: 79290, language: "TypeScript", license: "Apache 2.0", singleBinary: false, created: "2025-08-31", docs: "https://docs.claude-mem.ai/",
    deployment: "Local CLI", storage: "SQLite+Chroma", integration: "Hooks (5)", proxy: false, webUi: true, offline: true,
    unit: "Observation (text)",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 4,
    fulltext: true, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: true, searchModes: 3, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: true, p_gemini: true, p_copilot: true, p_cursor: false, p_windsurf: false, p_openclaw: true, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "mem0",
    name: "Mem0",
    url: "https://github.com/mem0ai/mem0",
    description: "Memory-as-a-Service platform with best published benchmarks",
    stars: 56958, language: "Python", license: "Apache 2.0", singleBinary: false, created: "2023-06-20", docs: "https://docs.mem0.ai/",
    deployment: "Lib/Self-host/Cloud", storage: "Qdrant", integration: "API/SDK", proxy: false, webUi: true, offline: false,
    unit: "Memory (text)",
    entities: true, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 6,
    fulltext: true, semantic: true, hybrid: true, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: "add-only", contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: true,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: true, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "91.6", b_longmemeval: "94.8", b_personamem: "—", b_token: "—", b_methodology: true,
  },
  {
    id: "engram",
    name: "engram",
    url: "https://github.com/Gentleman-Programming/engram",
    description: "Go binary agent memory with conflict surfacing and TUI",
    stars: 3825, language: "Go", license: "MIT", singleBinary: true, created: "2026-02-16", docs: "https://github.com/Gentleman-Programming/engram/blob/main/DOCS.md",
    deployment: "Local bin / Cloud (opt-in)", storage: "SQLite+FTS5", integration: "MCP+Hooks (19)", proxy: false, webUi: true, offline: true,
    unit: "Memory (What/Why/Where/Learned)",
    entities: false, actions: false, keywords: true, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: true, source: false, originTrust: false, emotional: false, conflict: true, layeredMemory: false, timeTravel: true, schemaFields: 6,
    fulltext: true, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: true, searchModes: 4, dataSources: 1,
    decay: false, supersede: true, contradiction: true, quarantine: false, autoResolve: false, trustModel: false, explicitForget: true,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: true, p_gemini: true, p_copilot: false, p_cursor: true, p_windsurf: true, p_openclaw: false, p_hermes: false, p_pi: true, p_antigravity: true,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "graphiti",
    name: "Graphiti",
    url: "https://github.com/getzep/graphiti",
    description: "Temporal knowledge graph engine (powers Zep)",
    stars: 26688, language: "Python", license: "Apache 2.0", singleBinary: false, created: "2024-08-08", docs: "https://github.com/getzep/graphiti#readme",
    deployment: "Library", storage: "Graph DB", integration: "Library", proxy: false, webUi: false, offline: true,
    unit: "Fact (graph node)",
    entities: true, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: true, timeTravel: true, schemaFields: 8,
    fulltext: true, semantic: true, hybrid: true, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: true, supersede: true, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: false, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "cognee",
    name: "Cognee",
    url: "https://github.com/topoteretes/cognee",
    description: "Memory control plane with remember/recall/forget/improve API",
    stars: 17559, language: "Python", license: "Apache 2.0", singleBinary: false, created: "2023-08-16", docs: "https://docs.cognee.ai/",
    deployment: "Lib/Cloud", storage: "Graph+Vector", integration: "API+Hooks", proxy: false, webUi: true, offline: false,
    unit: "Fact (graph+vec)",
    entities: true, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 10,
    fulltext: true, semantic: true, hybrid: true, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: true,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: true, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "byterover",
    name: "ByteRover",
    url: "https://github.com/campfirein/byterover-cli",
    description: "Context tree with git-like VC, strongest benchmarks (LoCoMo 96.1)",
    stars: 4796, language: "TypeScript", license: "Elastic 2.0", singleBinary: false, created: "2025-06-19", docs: "https://docs.byterover.dev/",
    deployment: "Local CLI / Cloud", storage: "SQLite+Context tree", integration: "MCP+REPL", proxy: false, webUi: true, offline: true,
    unit: "Context node (tree)",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: true, schemaFields: 6,
    fulltext: true, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: true, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: false, p_gemini: false, p_copilot: true, p_cursor: true, p_windsurf: true, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "96.1", b_longmemeval: "92.8", b_personamem: "—", b_token: "—", b_methodology: true,
  },
  {
    id: "memvid",
    name: "Memvid",
    url: "https://github.com/memvid/memvid",
    description: "Single-file memory (.mv2) with Smart Frames and time-travel",
    stars: 15583, language: "Rust", license: "Apache 2.0", singleBinary: true, created: "2025-05-27", docs: "https://docs.memvid.com/",
    deployment: "Lib/Local file", storage: "Single .mv2 file", integration: "SDK", proxy: false, webUi: false, offline: true,
    unit: "Smart Frame",
    entities: false, actions: false, keywords: true, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: true, timeTravel: true, schemaFields: 8,
    fulltext: true, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: true, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: false, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "+35% SOTA", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: true,
  },
  {
    id: "memori",
    name: "Memori",
    url: "https://github.com/MemoriLabs/Memori",
    description: "Agent-native memory (captures execution, not just conversation)",
    stars: 14979, language: "Python", license: "Apache 2.0", singleBinary: false, created: "2025-07-24", docs: "https://memorilabs.ai/docs/",
    deployment: "Cloud / BYODB", storage: "Cloud", integration: "SDK/MCP", proxy: false, webUi: true, offline: false,
    unit: "Memory entry",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 6,
    fulltext: true, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: true, p_windsurf: false, p_openclaw: true, p_hermes: true, p_pi: false, p_antigravity: false,
    b_locomo: "81.95", b_longmemeval: "—", b_personamem: "—", b_token: "95% fewer", b_methodology: true,
  },
  {
    id: "everos",
    name: "EverOS",
    url: "https://github.com/EverMind-AI/EverOS",
    description: "Self-evolving agent memory with evaluation framework",
    stars: 5755, language: "Python", license: "Apache 2.0", singleBinary: false, created: "2025-10-28", docs: "https://docs.evermind.ai/",
    deployment: "Lib/MCP", storage: "Vector DB", integration: "MCP", proxy: false, webUi: false, offline: true,
    unit: "Memory entry",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 8,
    fulltext: true, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: true, p_gemini: true, p_copilot: false, p_cursor: true, p_windsurf: false, p_openclaw: true, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "✅", b_longmemeval: "✅", b_personamem: "—", b_token: "—", b_methodology: true,
  },
  {
    id: "tencentdb",
    name: "TencentDB-AM",
    url: "https://github.com/Tencent/TencentDB-Agent-Memory",
    description: "Mermaid symbolic memory, L0→L3 pyramid, 61% token reduction",
    stars: 4347, language: "TypeScript", license: "MIT", singleBinary: false, created: "2026-04-07", docs: "https://github.com/Tencent/TencentDB-Agent-Memory#readme",
    deployment: "Plugin (OpenClaw)", storage: "SQLite+sqlite-vec", integration: "Plugin hooks", proxy: false, webUi: false, offline: true,
    unit: "Atom/Scenario/Persona",
    entities: true, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: true, timeTravel: false, schemaFields: 12,
    fulltext: true, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: true,
    p_claude: false, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: true, p_hermes: true, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "76%", b_token: "61%", b_methodology: true,
  },
  {
    id: "yesmem",
    name: "YesMem",
    url: "https://github.com/carsteneu/yesmem",
    description: "Project continuity layer with deepest data model and proxy collapse",
    stars: 10, language: "Go", license: "Apache 2.0", singleBinary: true, created: "2026-04-09", docs: "https://github.com/carsteneu/yesmem/blob/main/Features.md",
    deployment: "Local binary", storage: "SQLite+Vector", integration: "Proxy+MCP+Hooks", proxy: true, webUi: false, offline: true,
    unit: "Learning V2 (structured)",
    entities: true, actions: true, keywords: true, anticipatedQueries: true, triggerRules: true, domainTag: true, taskType: true, context: true, source: true, originTrust: true, emotional: true, conflict: true, layeredMemory: false, timeTravel: true, schemaFields: 22,
    fulltext: true, semantic: true, hybrid: true, deep: true, codeGraph: true, docsSearch: true, factQuery: true, timeline: true, searchModes: 9, dataSources: 4,
    decay: true, supersede: true, contradiction: true, quarantine: true, autoResolve: true, trustModel: true, explicitForget: true,
    autoExtract: true, contentPreproc: true, dedup: true, qualityRefine: true, narrative: true, clustering: true, recurrence: true, persona: true,
    p_claude: true, p_codex: true, p_opencode: true, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "0.87", b_longmemeval: "—", b_personamem: "—", b_token: "~30% proxy", b_methodology: true,
  },
  {
    id: "ai-memory",
    name: "ai-memory",
    url: "https://github.com/akitaonrails/ai-memory",
    description: "Git-versioned markdown wiki, zero LLM mode, cross-agent handoffs",
    stars: 341, language: "Rust", license: "MIT", singleBinary: true, created: "2026-05-21", docs: "https://github.com/akitaonrails/ai-memory/blob/main/docs/ARCHITECTURE.md",
    deployment: "Local binary", storage: "Git wiki (md)", integration: "MCP+Hooks", proxy: false, webUi: true, offline: true,
    unit: "Wiki page (md)",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: true, schemaFields: 6,
    fulltext: true, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 2, dataSources: 1,
    decay: false, supersede: true, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: true, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: true, p_gemini: true, p_copilot: false, p_cursor: true, p_windsurf: false, p_openclaw: true, p_hermes: false, p_pi: true, p_antigravity: true,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "memory-palace",
    name: "Memory Palace",
    url: "https://github.com/AGI-is-going-to-arrive/Memory-Palace",
    description: "Forgetting engine, snapshot rollback, intent-aware search, 4 maintenance engines",
    stars: 300, language: "Python", license: "MIT", singleBinary: false, created: "2026-02-19", docs: "https://github.com/AGI-is-going-to-arrive/Memory-Palace/blob/main/docs/README_EN.md",
    deployment: "Docker / local Python", storage: "SQLite+sqlite-vec", integration: "MCP+Skills", proxy: false, webUi: true, offline: true,
    unit: "Memory entry",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: true, timeTravel: true, schemaFields: 8,
    fulltext: true, semantic: true, hybrid: true, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 3, dataSources: 1,
    decay: true, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: true, qualityRefine: false, narrative: false, clustering: true, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: true, p_gemini: true, p_copilot: false, p_cursor: true, p_windsurf: true, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: true,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "mempalace",
    name: "MemPalace",
    url: "https://github.com/MemPalace/mempalace",
    description: "Verbatim storage, palace metaphor, 96.6% LongMemEval raw retrieval",
    stars: 52973, language: "Python", license: "MIT", singleBinary: false, created: "2026-04-05", docs: "https://mempalaceofficial.com/concepts/the-palace.html",
    deployment: "Local CLI", storage: "ChromaDB (pluggable)", integration: "CLI + MCP", proxy: false, webUi: false, offline: true,
    unit: "Verbatim text (no summarization)",
    entities: true, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 5,
    fulltext: false, semantic: true, hybrid: true, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 2,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: true, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "88.9", b_longmemeval: "96.6", b_personamem: "—", b_token: "—", b_methodology: true,
  },
  {
    id: "agentmemory",
    name: "agentmemory",
    url: "https://github.com/rohitg00/agentmemory",
    description: "53 MCP tools, 12 hooks, 4-tier lifecycle, 3-way RRF, pi native",
    stars: 19053, language: "TypeScript", license: "Apache 2.0", singleBinary: false, created: "2026-02-25", docs: "https://github.com/rohitg00/agentmemory#readme",
    deployment: "Local server (npm)", storage: "SQLite (0 external DBs)", integration: "MCP + Hooks (12)", proxy: false, webUi: true, offline: true,
    unit: "Memory entry (structured, confidence-scored)",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: true, timeTravel: false, schemaFields: 8,
    fulltext: true, semantic: true, hybrid: true, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: true, supersede: true, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: true,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: true, p_gemini: true, p_copilot: true, p_cursor: true, p_windsurf: false, p_openclaw: true, p_hermes: true, p_pi: true, p_antigravity: true,
    b_locomo: "—", b_longmemeval: "95.2", b_personamem: "—", b_token: "92% fewer", b_methodology: true,
  },
  {
    id: "obsidian-mind",
    name: "obsidian-mind",
    url: "https://github.com/breferrari/obsidian-mind",
    description: "Obsidian vault template, markdown-native memory, QMD semantic search",
    stars: 2715, language: "TypeScript", license: "MIT", singleBinary: false, created: "2026-02-28", docs: "https://github.com/breferrari/obsidian-mind#readme",
    deployment: "Obsidian vault + npm", storage: "Markdown + QMD/SQLite", integration: "CLI + MCP", proxy: false, webUi: true, offline: true,
    unit: "Markdown note (wiki)",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 4,
    fulltext: true, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 2, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: false, p_gemini: true, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "nocturne",
    name: "nocturne",
    url: "https://github.com/Dataojitori/nocturne_memory",
    description: "Rollbackable, visual LTM for MCP agents, no vector RAG",
    stars: 1150, language: "Python", license: "MIT", singleBinary: false, created: "2025-12-25", docs: "https://github.com/Dataojitori/nocturne_memory#readme",
    deployment: "Local MCP server", storage: "SQLite", integration: "MCP", proxy: false, webUi: true, offline: true,
    unit: "Memory entry",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: true, schemaFields: 5,
    fulltext: true, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "token-savior",
    name: "token-savior",
    url: "https://github.com/Mibayy/token-savior",
    description: "Claims 100% benchmark, -77% tokens, -76% time, MCP",
    stars: 912, language: "Python", license: "MIT", singleBinary: false, created: "2026-03-30", docs: "https://github.com/Mibayy/token-savior#readme",
    deployment: "MCP server", storage: "?", integration: "MCP", proxy: false, webUi: false, offline: true,
    unit: "Memory entry",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 4,
    fulltext: false, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "-77%", b_methodology: false,
  },
  {
    id: "opencode-mem",
    name: "opencode-mem",
    url: "https://github.com/tickernelz/opencode-mem",
    description: "OpenCode plugin, local vector DB for persistent agent memory",
    stars: 787, language: "TypeScript", license: "?", singleBinary: false, created: "2026-01-10", docs: "https://github.com/tickernelz/opencode-mem#readme",
    deployment: "OpenCode plugin", storage: "Local vector DB", integration: "Plugin (OpenCode)", proxy: false, webUi: false, offline: true,
    unit: "Vector entry",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 3,
    fulltext: false, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: false, p_codex: false, p_opencode: true, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "stash",
    name: "stash",
    url: "https://github.com/alash3al/stash",
    description: "Go + Postgres, episodes/facts/working context model",
    stars: 701, language: "Go", license: "Apache 2.0", singleBinary: true, created: "2026-04-24", docs: "https://github.com/alash3al/stash#readme",
    deployment: "Local binary", storage: "Postgres", integration: "MCP", proxy: false, webUi: false, offline: true,
    unit: "Episode + Fact + Context",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: true, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 6,
    fulltext: true, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "mex",
    name: "mex",
    url: "https://github.com/theDakshJaitly/mex",
    description: "Project memory scaffold + drift detection CLI",
    stars: 732, language: "TypeScript", license: "MIT", singleBinary: false, created: "2026-03-21", docs: "https://github.com/theDakshJaitly/mex#readme",
    deployment: "CLI tool", storage: "Structured scaffold", integration: "CLI", proxy: false, webUi: false, offline: true,
    unit: "Scaffold entry",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 4,
    fulltext: false, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "vestige",
    name: "vestige",
    url: "https://github.com/samvallad33/vestige",
    description: "FSRS-6 spaced repetition, 29 brain modules, 3D dashboard, Rust binary",
    stars: 540, language: "Rust", license: "AGPL-3.0", singleBinary: true, created: "2026-01-25", docs: "https://github.com/samvallad33/vestige#readme",
    deployment: "Local binary (22MB)", storage: "?", integration: "MCP", proxy: false, webUi: true, offline: true,
    unit: "Cognitive memory unit",
    entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 5,
    fulltext: false, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: true, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "wax", name: "Wax", url: "https://github.com/christopherkarani/Wax", description: "Swift/Metal, Apple Silicon, single-file, sub-ms RAG", stars: 742, language: "Swift", license: "Apache 2.0", singleBinary: true, created: "2026-01-20", docs: "https://github.com/christopherkarani/Wax#readme",
    deployment: "Single file (Apple Silicon)", storage: "Single file", integration: "Library", proxy: false, webUi: false, offline: true,
    unit: "Memory entry", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 3,
    fulltext: false, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: false, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "memomind", name: "MemoMind", url: "https://github.com/24kchengYe/MemoMind", description: "GPU-accelerated, local, zero cloud, Claude Code", stars: 716, language: "Python", license: "?", singleBinary: false, created: "2026-03-15", docs: "https://github.com/24kchengYe/MemoMind#readme",
    deployment: "Local Python", storage: "Local vector DB", integration: "MCP", proxy: false, webUi: false, offline: true,
    unit: "Memory entry", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 4,
    fulltext: false, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "memorix", name: "memorix", url: "https://github.com/AVIDS2/memorix", description: "Cross-agent MCP memory, 6 platforms", stars: 433, language: "TypeScript", license: "Apache 2.0", singleBinary: false, created: "2026-02-14", docs: "https://github.com/AVIDS2/memorix#readme",
    deployment: "MCP server", storage: "?", integration: "MCP", proxy: false, webUi: false, offline: true,
    unit: "Memory entry", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 4,
    fulltext: false, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: false, p_gemini: true, p_copilot: true, p_cursor: true, p_windsurf: true, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "octopoda", name: "Octopoda-OS", url: "https://github.com/RyjoxTechnologies/Octopoda-OS", description: "Memory OS: loop detection, agent messaging, crash recovery", stars: 337, language: "Python", license: "?", singleBinary: false, created: "2026-04-02", docs: "https://github.com/RyjoxTechnologies/Octopoda-OS#readme",
    deployment: "Local server", storage: "?", integration: "?", proxy: false, webUi: false, offline: true,
    unit: "Memory entry", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 4,
    fulltext: false, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "icarus", name: "icarus", url: "https://github.com/esaradev/icarus-memory-infra", description: "Provenance, rollback, 3-layer: working+session+wiki", stars: 285, language: "Python", license: "MIT", singleBinary: false, created: "2026-03-24", docs: "https://github.com/esaradev/icarus-memory-infra#readme",
    deployment: "Local Python", storage: "Markdown wiki + archive", integration: "?", proxy: false, webUi: false, offline: true,
    unit: "Working + session + wiki layers", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: true, timeTravel: true, schemaFields: 5,
    fulltext: false, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: true, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: false, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "shodh", name: "shodh-memory", url: "https://github.com/varun29ankuS/shodh-memory", description: "Cognitive: learns from use, forgets irrelevant, Rust", stars: 215, language: "Rust", license: "?", singleBinary: true, created: "2025-12-03", docs: "https://github.com/varun29ankuS/shodh-memory#readme",
    deployment: "Local binary", storage: "?", integration: "?", proxy: false, webUi: false, offline: true,
    unit: "Cognitive entry", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 4,
    fulltext: false, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: true, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: false, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "clawmem", name: "ClawMem", url: "https://github.com/yoloshii/ClawMem", description: "On-device, Claude/OpenClaw/Hermes, hooks+MCP+hybrid RAG", stars: 176, language: "TypeScript", license: "MIT", singleBinary: false, created: "2026-02-06", docs: "https://github.com/yoloshii/ClawMem#readme",
    deployment: "Local server", storage: "?", integration: "Hooks + MCP", proxy: false, webUi: false, offline: true,
    unit: "Memory entry", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 4,
    fulltext: true, semantic: true, hybrid: true, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: true, p_hermes: true, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "moltbrain", name: "MoltBrain", url: "https://github.com/nhevers/MoltBrain", description: "Long-term memory for OpenClaw & MoltBook", stars: 250, language: "TypeScript", license: "?", singleBinary: false, created: "2026-01-26", docs: "https://github.com/nhevers/MoltBrain#readme",
    deployment: "Plugin", storage: "?", integration: "Plugin", proxy: false, webUi: false, offline: true,
    unit: "Memory entry", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 3,
    fulltext: false, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: false, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: true, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "context-infra", name: "context-infra", url: "https://github.com/grapeot/context-infrastructure", description: "Memory + rules + skills + scheduled observations", stars: 503, language: "Python", license: "?", singleBinary: false, created: "2026-03-16", docs: "https://github.com/grapeot/context-infrastructure#readme",
    deployment: "Local Python", storage: "?", integration: "MCP", proxy: false, webUi: false, offline: true,
    unit: "Context entry", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 4,
    fulltext: false, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "openviking", name: "OpenViking", url: "https://github.com/volcengine/OpenViking", description: "ByteDance context DB, filesystem paradigm, L0/L1/L2 tiers, LoCoMo 82%", stars: 24815, language: "Python", license: "AGPL-3.0", singleBinary: false, created: "2026-01-05", docs: "https://github.com/volcengine/OpenViking/tree/main/docs",
    deployment: "Self-hosted", storage: "Context DB (filesystem paradigm)", integration: "API", proxy: false, webUi: true, offline: true,
    unit: "Context node (filesystem tree)", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: true, timeTravel: false, schemaFields: 6,
    fulltext: false, semantic: true, hybrid: true, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 2, dataSources: 3,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: true, p_hermes: true, p_pi: false, p_antigravity: false,
    b_locomo: "82.1", b_longmemeval: "—", b_personamem: "—", b_token: "91%", b_methodology: true,
  },
  {
    id: "hindsight", name: "hindsight", url: "https://github.com/vectorize-io/hindsight", description: "Self-improving agentic memory that learns from feedback (vectorize.io)", stars: 14954, language: "Python", license: "MIT", singleBinary: false, created: "2025-10",
    deployment: "SDK/Library", storage: "Vector store", integration: "Python API", proxy: false, webUi: false, offline: false,
    unit: "Memory entry", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 3,
    fulltext: false, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: false, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "memoir", name: "memoir", url: "https://github.com/zhangfengcdt/memoir", description: "Hierarchical agent memory with git-like branch/commit/merge/rollback semantics", stars: 554, language: "Python", license: "Apache-2.0", singleBinary: false, created: "2025-08",
    deployment: "Plugin (Claude Code, Codex)", storage: "Hierarchical paths", integration: "Plugin", proxy: false, webUi: false, offline: true,
    unit: "Hierarchical memory node", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: true, timeTravel: true, schemaFields: 4,
    fulltext: false, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: true, searchModes: 1, dataSources: 1,
    decay: false, supersede: true, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "fidelis", name: "fidelis", url: "https://github.com/hermes-labs-ai/fidelis", description: "Non-LLM agent memory, BM25 + rerank, 83.2% R@1 on LongMemEval-S", stars: 20, language: "Python", license: "MIT", singleBinary: false, created: "2026-03",
    deployment: "MCP server + hooks", storage: "BM25 index", integration: "MCP + hooks", proxy: false, webUi: false, offline: true,
    unit: "Memory entry", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 3,
    fulltext: true, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: true, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "83.2% R@1", b_personamem: "—", b_token: "—", b_methodology: true,
  },
  {
    id: "arcrift", name: "ArcRift", url: "https://github.com/Eshaan-Nair/ArcRift", description: "Local persistent memory layer, Chrome extension + MCP, sqlite-vec RAG", stars: 75, language: "TypeScript", license: "MIT", singleBinary: false, created: "2026-04",
    deployment: "Local server + Chrome ext", storage: "sqlite-vec", integration: "MCP + browser", proxy: false, webUi: true, offline: true,
    unit: "Memory entry", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 4,
    fulltext: false, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "gitmem", name: "gitmem", url: "https://github.com/dev-boz/gitmem", description: "Git-native shared memory for CLI agents, three-tier (Spaces / Hierarchical / Active)", stars: 27, language: "Python", license: "MIT", singleBinary: false, created: "2026-04",
    deployment: "Local CLI", storage: "Markdown + git", integration: "CLI", proxy: false, webUi: false, offline: true,
    unit: "Markdown memory file", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: true, timeTravel: true, schemaFields: 3,
    fulltext: true, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: true, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: true, p_opencode: true, p_gemini: true, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "aipass", name: "AIPass", url: "https://github.com/AIOSAI/AIPass", description: "Persistent agent workspace with .trinity memory submodule + CLI", stars: 148, language: "Python", license: "MIT", singleBinary: false, created: "2026-02",
    deployment: "Local CLI", storage: "Filesystem", integration: "CLI", proxy: false, webUi: false, offline: true,
    unit: "Workspace entry", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 3,
    fulltext: false, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "letta", name: "Letta", url: "https://github.com/letta-ai/letta", description: "Stateful agent platform with hierarchical memory (core/recall/archival), formerly MemGPT", stars: 23011, language: "Python", license: "Apache-2.0", singleBinary: false, created: "2023-10",
    deployment: "Server + SDK", storage: "Postgres + vector", integration: "SDK + REST", proxy: false, webUi: true, offline: true,
    unit: "Memory block", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: true, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: true, timeTravel: false, schemaFields: 5,
    fulltext: true, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 2, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: true,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: true,
  },
  {
    id: "supermemory", name: "Supermemory", url: "https://github.com/supermemoryai/supermemory", description: "Multimodal AI memory engine for the web (documents/links/media), Chrome ext + MCP + hosted", stars: 22731, language: "TypeScript", license: "MIT", singleBinary: false, created: "2024-02",
    deployment: "SaaS + self-host", storage: "Vector + KV", integration: "MCP + REST + browser", proxy: false, webUi: true, offline: true,
    unit: "Memory document", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: true, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 4,
    fulltext: true, semantic: true, hybrid: true, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 3, dataSources: 3,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: true,
    autoExtract: false, contentPreproc: true, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "#1", b_personamem: "—", b_token: "—", b_methodology: true,
  },
  {
    id: "honcho", name: "Honcho", url: "https://github.com/plastic-labs/honcho", description: "Memory library for stateful agents with theory-of-mind reasoning and user-level personalization", stars: 4422, language: "Python", license: "AGPL-3.0", singleBinary: false, created: "2024-04",
    deployment: "Server + SDK", storage: "Postgres", integration: "SDK + REST + MCP", proxy: false, webUi: true, offline: true,
    unit: "User-scoped memory", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: true, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 4,
    fulltext: false, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: true,
    p_claude: true, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "langmem", name: "LangMem", url: "https://github.com/langchain-ai/langmem", description: "LangChain memory toolkit with managers, namespaces, and LangGraph integration", stars: 1473, language: "Python", license: "MIT", singleBinary: false, created: "2025-02",
    deployment: "Library", storage: "Pluggable backends", integration: "LangChain/LangGraph", proxy: false, webUi: false, offline: true,
    unit: "Memory namespace", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 3,
    fulltext: false, semantic: true, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: true, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: false, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
  {
    id: "nanobot", name: "Nanobot", url: "https://github.com/obot-platform/nanobot", description: "Go-based multi-agent MCP host with persistent memory and skills (obot-platform)", stars: 1321, language: "Go", license: "Apache-2.0", singleBinary: true, created: "2025-05",
    deployment: "Local binary", storage: "Filesystem", integration: "MCP", proxy: false, webUi: false, offline: true,
    unit: "Memory file", entities: false, actions: false, keywords: false, anticipatedQueries: false, triggerRules: false, domainTag: false, taskType: false, context: false, source: false, originTrust: false, emotional: false, conflict: false, layeredMemory: false, timeTravel: false, schemaFields: 3,
    fulltext: false, semantic: false, hybrid: false, deep: false, codeGraph: false, docsSearch: false, factQuery: false, timeline: false, searchModes: 1, dataSources: 1,
    decay: false, supersede: false, contradiction: false, quarantine: false, autoResolve: false, trustModel: false, explicitForget: false,
    autoExtract: false, contentPreproc: false, dedup: false, qualityRefine: false, narrative: false, clustering: false, recurrence: false, persona: false,
    p_claude: false, p_codex: false, p_opencode: false, p_gemini: false, p_copilot: false, p_cursor: false, p_windsurf: false, p_openclaw: false, p_hermes: false, p_pi: false, p_antigravity: false,
    b_locomo: "—", b_longmemeval: "—", b_personamem: "—", b_token: "—", b_methodology: false,
  },
];
